### ISSUE TITLE
Transformer library

### ISSUE THREAD

**Issue by tonilopezmr** [PaNaVTEC/Clean-Contacts#9]
Why not used you the transformer library in the presentation layer?

**Comment by PaNaVTEC** [comment]
Because when I'm speaking I need an example of what is a mapper, some people are not familiarized with this term, if I use the library in all the parts of the code I cannot explain this concept well :)

Altought if I remember well, I tought I had any problem when using in a Java module, but I'm not sure.

**Comment by tonilopezmr** [comment]
Ahhh okey!!! I couldn't go :(

Thanks and very nice code
